name: Laravel

on:
    push:
        branches: ['dev']
    pull_request:
        branches: ['master']

jobs:
    laravel-tests:
        runs-on: ubuntu-latest

        steps:
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
            - uses: actions/checkout@v3
            - name: Copy .env
              run: php -r "file_exists('.env') || copy('.env.example', '.env');"
            - name: Install PHP Dependencies
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            - name: Install PNPM
              run: sudo npm install -g pnpm
            - name: Check PNPM version
              run: pnpm -v
            - name: Install Node.js Dependencies
              run: pnpm install
            - name: Build frontend
              run: pnpm build
            - name: Check frontend linter via Eslint
              run: pnpm linter
            - name: Check frontend formatter via Prettier
              run: pnpm formatter
            - name: Generate key
              run: php artisan key:generate
            - name: Directory Permissions
              run: chmod -R 777 storage bootstrap/cache
            - name: Create Database
              run: |
                  mkdir -p database
                  touch database/database.sqlite
            - name: Execute tests (Unit and Feature tests) via PEST
              env:
                  DB_CONNECTION: sqlite
                  DB_DATABASE: database/database.sqlite
              run: php artisan test
            - name: Check backend code style via Laravel Pint
              run: vendor/bin/pint --test -v
